### ISSUE TITLE
Electrical Library (Datasheets, Application Notes, Certificates, Catalogs)

### ISSUE THREAD

**Issue by arol-varesi** [ArolUTEA/Xplorer#12]
# Gestione Libreria Documentazione Elettrica
Si tratta di implementare una funzionalità parallela alla sola gestione dei codici elettrici in modo da gestire agevolmente la Libreria di tutta la documentazione relativa alla componentistica elettrica.
Attualmente nel programma vi è la possibilità di abbinare un solo documento (solitamente il datasheet) ad ogni codice di magazzino; questo si presenta come una limitazione e quindi si propone quanto segue.
## DB Libreria
Si propone di introdurre un database (o una Table dedicata) nel quale ogni record rappresenta un'unita documentale. Si potrebbe pensare ad una struttura di campi simile a :

Campo | Tipo | Descrizione 
----|----|----
ID | ID |
Tipo | ID Tipo | Tipologia di documento (es. Datasheet, Application note, ...
Titolo | Stringa | Titolo del documento
Versione | Stringa | Versione del dcumento (ad. esempio 2017/04 )
File | RelativePath | Percorso del File
Link | URL | eventuale percorso del documento in Internet

Inoltre sarà utile creare una tabella di  link tra componente e documento, in questo modo sarà possibile attribuire più documenti allo stesso componente o più componenti allo stesso documento... 

Ovviamente dovrà essere creata nel software una sezione dedicata alla gestione della documentazione, ricercabile e gestibile indipendentemente dai componenti elettrici.

**Comment by arol-parodi** [comment]
# **Todo:**
In una prima ipotesi proviamo a partire considerando l'introduzione di nuove tabelle all'interno del database esistente.

## **Tabella "documentazione"**
Lo scopo della tabella è quello di raccogliere i link di tutti i documenti, informazioni sul tipo di documento, versioning, percorso del file su server locale, percorso del file su Internet.
 
La struttura della tabella sarà composta dai seguenti campi:

Campo | Tipo | Descrizione 
----|----|----
ID | Integer Unique |
Tipo | Integer | Tipologia di documento (sarà un numero intero che rappresenterà l'ID di una tabella "tipologia documentazione")
Titolo | Stringa | Titolo del documento
Versione | Stringa | Versione del dcumento (ad. esempio 2017/04 )
File | RelativePath | Percorso del File
Link | URL | eventuale percorso del documento in Internet

## **Tabella "tipologiaDocumentazione"**

Campo | Tipo | Descrizione
----|----|----
ID | Integer Unique | 
Tipo | Integer | Valore intero che rappresenta la tipologia (es.: 1 = datasheet, 2 = application note, etc.
Descrizione | Stringa | Descrizione della tipologia.

Qui sotto una prima idea di come potrebbero essere i campi:

ID | Tipo | Descrizione
----|----|----
0 | 1 | Datasheet
1 | 2 | User Manual
2 | 3 | Electrical Drawing
3 | 4 | Application Note
4 | 5 | Offerta Economica

## **Tabella "linkToDoc"**
Contiene il link tra il ArolCode ed il/i documento/i legati al codice i-esimo.
Sarà quindi una lista di legami tra un codice Arol ed uno o più elementi della tabella "documentazione".
La sua struttura sarà:

Campo | Tipo | Descrizione 
----|----|----
ID | Integer Unique |
ArolCode | Stringa | Codice Arol del componente
LinkDoc | Intero | ID del relativo elemento della tabella "documentazione"

Il campo ArolCode non dovrà essere di tipo "Unique"!!

Esempio:

ID | ArolCode | LinkDoc
----|----|----
0 | HHCAVO_CV123 | 145
1 | HHCAVO_CV123 | 193
2 | HHCAVO_CV123 | 245 

## **Integrazione nel software**

Dal menù a tendina "Database", è possibile selezionare la voce "New document...".
Si apre un form in cui è possibile compilare i campi necessari all'aggiunta di un nuovo documento.
I campi saranno i seguenti:

**Tipo:** sarà una combobox (menù di selezione che deve essere popolata secondo il contenuto della tabella "tipologiaDocumentazione").
**Titolo:** sarà una textbox in cui inserire un titolo del documento.
**Versione:** sarà una textbox in cui inserire l'indice di revisione del documento.
**File:** sarà un oggetto di browser di explorer per poter selezionare il path in cui il documento è salvato.
**Url:** sarà una textbox in cui inserire il collegamento internet "url" al documento.

**Comment by arol-parodi** [comment]
Closed with release 1.2.7.11 #20
