### ISSUE TITLE
Nella finestra "Dettagli" in caso di selezione di componente senza dati, rimangono attivi i dati del componente precedentemente visualizzato

### ISSUE THREAD

**Issue by arol-varesi** [ArolUTEA/Xplorer#18]
Selezionato componente senza dati
![immagine](https://user-images.githubusercontent.com/38038608/47362777-7be84d80-d6d5-11e8-82c5-26be8651e447.png)
Selezionato componente con dati
![immagine](https://user-images.githubusercontent.com/38038608/47362826-9c180c80-d6d5-11e8-8514-5fe393147e11.png)
Riselezionato componente senza dati ma rimangono visualizzati i dati del precedente
![immagine](https://user-images.githubusercontent.com/38038608/47362856-b18d3680-d6d5-11e8-9cb7-83555db7be69.png)

**Comment by arol-parodi** [comment]
Closed, #19
