### ISSUE TITLE
New Code: panel 4 clear

### ISSUE THREAD

**Issue by ArolUTEA** [ArolUTEA/Xplorer#3]
Quando si cambia la selezione da "famiglia di componente" a "generico", è necessario effettuare la pulizia del pannello numero 4 "descrizione". (vedi screenshot)
![tempimg](https://user-images.githubusercontent.com/37367817/38140776-97fc2a2a-3435-11e8-8741-e6c517316952.jpg)

**Comment by arol-parodi** [comment]
La pulizia del pannello n°4 come anche quella delle textboxes e dei combobox deve essere fatta con il cambiamento di selezione di tutti i radiobutton, della selezione della famiglia componente e della pressione del pulsante btnCreaFileTxt. Sono state create due funzioni clearAndResetTextBoxes(), e clearAndResetComboBoxes() per effettuare queste operazioni.

Bisogna ora verificare che queste funzioni vengano chiamate nei momenti opportuni,

**Comment by arol-parodi** [comment]
Issue closed 12/04/2018.
