### ISSUE TITLE
Visualization of Code State (Obsolete, Cancelled, Spare Parts Only)

### ISSUE THREAD

**Issue by ArolUTEA** [ArolUTEA/Xplorer#8]
Gestione del codice annullato, aggiunta di una visualizzazione dedicata all'informazione di codice annullato

**Comment by arol-varesi** [comment]
## Gestionale Codici
Si chiede di aggiungere e gestire campi utili per la gestione dei codici, in particolare:
### Stato del codice
- In obsolescenza (sostituido da ...)
- Solo per ricambio
- Annullato
### Gestione del magazzino (opzionale e poco prioritario)
- Stock
- Lotto
- Data (ultima richiesta)

-----
## Note di implementazione
Si consiglia di utilizzare una tabella autonoma, separata dalla tabella codici ma collegata ad essa tramite il ArolCode.
Lo stato del codice deve poter essere evidente già nel risultato ricerca, ad esempio con sfondo di colere differente.

La gestione Stock e Lotti è utile per tenere traccia delle richieste che UTEA emette nei confronti del reparto di logistica magazzino. Per questo è anche necessario sapere l'ultima volta che è stata effettuata la richiesta... potrebbe essere comodo usare una gestione di tipo "log" nel quale viene mantenuta una tabella nel quale ogni record indica : ArolCode, Data, Stock e Lotto (più eventuali altri campi che potranno essere utili). La gestione potrebbe essere filtrando la lista per Codice, oppure per data. 
Il record con la data più recente contiene il valore di Stock e di Lotto piu recenti e quindi probabilmente quelli definitivi.

**Comment by arol-parodi** [comment]
## Azioni

Creare una tabella autonoma contenente i seguenti campi:

| Campo | Tipo    | Descrizione |
| --------|---------|-------|
| ID  | ID   |      |
| ArolCode | Stringa | Codice Arol compontente    |
| Stato | Intero | Valore intero che rappresenta lo stato |
| Data inserimento | Stringa | Data di inserimento codice |
| Inserito da | Stringa | Utente che ha effettuato la codifica |
| Codifica richiesta da | Stringa | Nome, Cognome e reparto di chi ha richiesto la codifica |
| Data modifica stato | Stringa | Data di modifica ultimo stato |
| Note | Stringa | Note al contorno |

### Stato:

- 0: codice attivo;

- 1: solo per ricambio;

- 2: in obsolescenza;

- 3: annullato;
### Data di inserimento:
Questo campo sarà popolato in fase di codifica del componente.
### Data di modifica stato:
Questo campo verrà aggiornato ad ogni modifica del campo _Stato_ e sarà rappresentativo della data relativa all'ultima modifica di stato.
### Note:
Conterrà le note al contorno (esempio: Sostituito da: _codiceArol_)

## Modifiche collegate
### Form
L'implementazione di questa nuova feature implica la creazione di un form di modifica del codice, ove, oltre a poter modificare i campi di _Codice Commerciale_, _Descrizione_, _Descrizione supplementare_, dovrà poter essere possibile modificare anche lo _Stato_ (attraverso dei radiobutton? forse è meglio un listbox) ed il campo _Note al contorno_. L'editing del campo _Note al contorno_ dovrà essere pilotato con delle frasi standard (es.: Sostituito da: _+codiceArol_), oppure liberamente editabile.
### DatagridView
Il valore contenuto nella colonna _Stato_ verrà rappresentato sul DatagridView con una colorazione differente dello sfondo della riga corrispondente al codice Arol; in particolare:

| Stato | Valore | Colore |
| ------ | ------- | -------- |
| Codice attivo | 0 | light green |
| Solo per ricambio| 1 | light yellow |
| In obsolescenza | 2 | light orange |
| Annullato | 3 | light red |

### Funzione accessoria
Molto probabilmente risulta necessario elaborare una funzione accessoria da utilizzarsi solo durante il primo popolamento della tabella. Questa funzione dovrà ricopiare tutti i codici contenuti nelle tabelle _codificati_ e _consumabili_, ed assegnare inizialmente lo stato di attivo a ciascun componente. L'assegnazione dello stato di annullato sarà poi modificato manualmente.
In un secondo momento si può pensare di recuperare le informazioni di _Data di inserimento_ e _Codifica richiesta da_, prelevandole automaticamente dal file Excel _CodificheELENCO.xls_.

**Comment by arol-parodi** [comment]
Closed with release 1.1.6.7.
An open point of this issue has been moved to issue #15 .
